import { VenteItem } from "./SuiviVentes";

// Fonction pour générer un ID aléatoire
const generateId = () => Math.random().toString(36).substr(2, 9);

// Génération des données de test pour les ventes
export const mockVentesData: VenteItem[] = [
  {
    id: generateId(),
    date: "2025-05-01",
    designation: "Filtre à huile",
    marqueProduit: "Bosch",
    marqueVehicule: "Renault",
    modele: "Clio",
    serie: "IV",
    categorie: "Filtration",
    quantite: 2,
    prixUnitaire: 12.5,
    total: 25.0,
    prixAchat: 8.75
  },
  {
    id: generateId(),
    date: "2025-05-02",
    designation: "Plaquettes de frein avant",
    marqueProduit: "Ferodo",
    marqueVehicule: "Peugeot",
    modele: "308",
    serie: "II",
    categorie: "Freinage",
    quantite: 1,
    prixUnitaire: 45.99,
    total: 45.99,
    prixAchat: 28.50
  },
  {
    id: generateId(),
    date: "2025-05-03",
    designation: "Batterie 60Ah",
    marqueProduit: "Varta",
    marqueVehicule: "Citroën",
    modele: "C3",
    serie: "III",
    categorie: "Électricité",
    quantite: 1,
    prixUnitaire: 89.99,
    total: 89.99,
    prixAchat: 62.50
  },
  {
    id: generateId(),
    date: "2025-05-04",
    designation: "Amortisseur arrière",
    marqueProduit: "KYB",
    marqueVehicule: "Volkswagen",
    modele: "Golf",
    serie: "VII",
    categorie: "Suspension",
    quantite: 2,
    prixUnitaire: 68.75,
    total: 137.5,
    prixAchat: 47.20
  },
  {
    id: generateId(),
    date: "2025-05-05",
    designation: "Courroie de distribution",
    marqueProduit: "Gates",
    marqueVehicule: "Renault",
    modele: "Megane",
    serie: "III",
    categorie: "Moteur",
    quantite: 1,
    prixUnitaire: 35.25,
    total: 35.25,
    prixAchat: 24.15
  },
  {
    id: generateId(),
    date: "2025-05-06",
    designation: "Liquide de refroidissement 5L",
    marqueProduit: "Total",
    marqueVehicule: "Universel",
    modele: "-",
    serie: "-",
    categorie: "Fluides",
    quantite: 3,
    prixUnitaire: 15.99,
    total: 47.97,
    prixAchat: 10.80
  },
  {
    id: generateId(),
    date: "2025-05-07",
    designation: "Bougie d'allumage",
    marqueProduit: "NGK",
    marqueVehicule: "Ford",
    modele: "Focus",
    serie: "III",
    categorie: "Allumage",
    quantite: 4,
    prixUnitaire: 8.50,
    total: 34.0,
    prixAchat: 5.25
  },
  {
    id: generateId(),
    date: "2025-05-08",
    designation: "Balais d'essuie-glace",
    marqueProduit: "Valeo",
    marqueVehicule: "Opel",
    modele: "Astra",
    serie: "K",
    categorie: "Visibilité",
    quantite: 2,
    prixUnitaire: 22.75,
    total: 45.5,
    prixAchat: 14.30
  },
  {
    id: generateId(),
    date: "2025-05-09",
    designation: "Disque de frein avant",
    marqueProduit: "Brembo",
    marqueVehicule: "BMW",
    modele: "Série 3",
    serie: "F30",
    categorie: "Freinage",
    quantite: 2,
    prixUnitaire: 75.50,
    total: 151.0,
    prixAchat: 52.80
  },
  {
    id: generateId(),
    date: "2025-05-10",
    designation: "Huile moteur synthétique 5W40 1L",
    marqueProduit: "Castrol",
    marqueVehicule: "Universel",
    modele: "-",
    serie: "-",
    categorie: "Fluides",
    quantite: 5,
    prixUnitaire: 9.99,
    total: 49.95,
    prixAchat: 6.75
  },
  {
    id: generateId(),
    date: "2025-05-11",
    designation: "Filtre à air",
    marqueProduit: "Mann",
    marqueVehicule: "Mercedes",
    modele: "Classe A",
    serie: "W176",
    categorie: "Filtration",
    quantite: 1,
    prixUnitaire: 18.50,
    total: 18.50,
    prixAchat: 12.25
  },
  {
    id: generateId(),
    date: "2025-05-12",
    designation: "Capteur ABS",
    marqueProduit: "Delphi",
    marqueVehicule: "Audi",
    modele: "A4",
    serie: "B8",
    categorie: "Électronique",
    quantite: 1,
    prixUnitaire: 65.75,
    total: 65.75,
    prixAchat: 43.20
  }
];